project_variable:
  # model_type choices: [realtime / onetime]
  # change model_config.model_name.losses and evaluation.metrics accordingly
  model_type: onetime 
  hidden_size: 256 # mini:256, small/medium:512, base:768
  max_length: 50
  max_pred_num: 2
  use_pt1: false
  use_pt2: false
  use_pt3: true

model_config:
  multi_sensor_pt2:
    losses:
    # - type: m4c_decoding_bce_with_mask # model_type: realtime
    - type: logit_bce # model_type: onetime
    model_type: ${project_variable.model_type}
    training_head_type: "pretraining"
    mmt:
      hidden_size: ${project_variable.hidden_size} # mini:256, small/medium:512, base:768
      num_attention_heads: 4 # mini:4, small:4, medium:8, base:12
      num_hidden_layers: 4 # original: 4 stacks
      max_dec_length: ${project_variable.max_length}
      max_pred_num: ${project_variable.max_pred_num}
      model_type: ${project_variable.model_type}
      training_head_type: "pretraining"
      hidden_dropout_prob: 0.1
    gru:
      hidden_size: ${project_variable.hidden_size} # /2 if bidirectional=true
      bidirectional: false
      batch_first: true
    data_in_dim:
      single_vital: 1
      double_vital: 2
      demographic: 15
    classifier:
      type: mlp
      params:
        in_dim: ${project_variable.hidden_size}
        out_dim: ${project_variable.max_pred_num}
    pt2_classifier:
      type: mlp
      params:
        in_dim: ${project_variable.hidden_size}
        out_dim: 2
    use_pt1: ${project_variable.use_pt1}
    use_pt2: ${project_variable.use_pt2}
    use_pt3: ${project_variable.use_pt3}

dataset_config:
  masked_girasoles_sensor:
      data_dir: ${env.data_dir}/datasets
      annotations:
        train:
        - girasoles_sensor/defaults/annotations/sensor_truncated_train.npy
        val:
        - girasoles_sensor/defaults/annotations/sensor_truncated_test.npy
        test:
        - girasoles_sensor/defaults/annotations/sensor_truncated_test.npy
      model_type: ${project_variable.model_type}
      max_seq_length: ${project_variable.max_length}
      max_pred_num: ${project_variable.max_pred_num}
      hidden_size: ${project_variable.hidden_size}
      answer_key: aki_labels # choices: ["aki_labels", "usg_labels", "temp"]
      use_pt1: ${project_variable.use_pt1}
      use_pt2: ${project_variable.use_pt2}

optimizer:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: Adam

evaluation:
  metrics:
  # - sequence_accuracy # model_type: realtime
  - accuracy # model_type: onetime

training:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 14000
    - 19000
    lr_ratio: 0.1
    log_interval: 100
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 2000
    max_updates: 20000
    checkpoint_interval: 1000
    evaluation_interval: 20001
    batch_size: 64
